name: Publish package to GitHub Packages
on: push
jobs:
  publish:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            java-version: '1.8'
            distribution: 'openjdk'
        - name: Publish package
          run: mvn --batch-mode deploy
          env:
            GITHUB_TOKEN: ${{ secret.JAVA_TOKEN }}
